# Generated by Django 5.2.1 on 2025-06-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("Phone_number", models.CharField(max_length=250)),
                ("message", models.TextField()),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Contact Table",
            },
        ),
    ]
